### ISSUE TITLE
Include steps to set up postgress server before migration

### ISSUE THREAD

**Issue by jonedavis** [TwilioDevEd/airtng-laravel#38]
Fails at `php artisan migrate`
```
 [PDOException]                                                              
  SQLSTATE[08006] [7] FATAL:  no PostgreSQL user name specified in startup p  
  acket         
```

Do we need to include steps to set up username and password for db?

**Comment by po5i** [comment]
@jonedavis did you test it out in #35 branch? I replaced postgres with sqlite as you can confirm in this GH actions job: https://github.com/TwilioDevEd/airtng-laravel/pull/35/checks?check_run_id=540510663

**Comment by jonedavis** [comment]
Closing :)
