### ISSUE TITLE
TwiML bin required?

### ISSUE THREAD

**Issue by jonedavis** [TwilioDevEd/airtng-laravel#39]
This is only project that uses TwiML. What's this used for? Also, the link in the comment below does not work. Can we update that to current link?

`# You need to create a TwiML app to use this project. # Create one at https://www.twilio.com/user/account/apps/add, # then use its "Sid" value here TWILIO_APPLICATION_SID=`

**Comment by po5i** [comment]
Can you point where that comment is located? I can't find it anywhere in this repo.

Regarding TwiML, This repo is responding with [a TwiML](https://github.com/TwilioDevEd/airtng-laravel/blob/80393f9d1c729ea893e76c86c87677f89b5ae16f/app/Http/Controllers/ReservationController.php#L88) in the same fashion [other do](https://github.com/TwilioDevEd/airtng-flask/blob/86200ad7f0ef49047399b137be74a10fa06c64ea/airtng_flask/views.py#L150). Is there any missing change here?

**Comment by jonedavis** [comment]
Closing, was in wrong branch.
